# Generated by Django 3.2.19 on 2023-07-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20230703_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinfo',
            name='test',
        ),
    ]
