# Generated by Django 3.2.19 on 2023-07-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_eventinfo_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_info',
            fields=[
                ('id', models.IntegerField(default=0, max_length=11, primary_key=True, serialize=False)),
                ('event_type', models.IntegerField(default=0, max_length=11)),
                ('event_date', models.DateTimeField()),
                ('event_location', models.CharField(default=0, max_length=200)),
                ('event_desc', models.CharField(default=0, max_length=200)),
                ('oldperson_id', models.IntegerField(default=0, max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='EventInfo',
        ),
    ]
