# Generated by Django 3.2.19 on 2023-07-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20230703_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='CREATEBY',
            field=models.IntegerField(blank=True, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='CREATED',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='DESCRIPTION',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='ISACTIVE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='REMOVE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='删除标志'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='UPDATEBY',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='UPDATED',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='hire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入职日期'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='工作人员id'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='id_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='imgset_dir',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图像目录'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='头像路径'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='resign_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='离职日期'),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='工作人员姓名'),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='事件发生的时间'),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='event_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='事件描述'),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='event_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='事件发生的地点'),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='event_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='事件id'),
        ),
        migrations.AlterField(
            model_name='event_info',
            name='oldperson_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='老人id'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='CREATEBY',
            field=models.IntegerField(blank=True, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='CREATED',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='DESCRIPTION',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='老人id'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='ISACTIVE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='REMOVE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='删除标志'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='UPDATEBY',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='UPDATED',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入养老院日期'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='离开养老院日期'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='firstguardian_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='第一监护人姓名'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='firstguardian_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='第一监护人电话'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='firstguardian_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='与第一监护人关系'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='firstguardian_wechat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='第一监护人微信'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='health_state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='健康状况'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='id_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='imgset_dir',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图像目录'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='头像路径'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='secondguardian_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='第二监护人姓名'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='secondguardian_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='第二监护人电话'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='secondguardian_relationship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='与第二监护人关系'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='secondguardian_wechat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='第二监护人微信'),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='老人姓名'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='CREATEBY',
            field=models.IntegerField(blank=True, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='CREATED',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='DATAFILTER',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='数据过滤'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='DESCRIPTION',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='EMAIL',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='系统管理员id'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='ISACTIVE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='MOBILE',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='移动电话'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='PHONE',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='Password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='REAL_NAME',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户真实姓名'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='REMOVE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='删除标志'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='SEX',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='UPDATEBY',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='UPDATED',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='UserName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='appversion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='检测app的版本号'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='defaultpage',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='缺省页面'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='jsonauth',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='用于app的权限控制'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='logoimage',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='qqopenid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用于第三方登录的凭证'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='theme',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='CREATEBY',
            field=models.IntegerField(blank=True, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='CREATED',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='DESCRIPTION',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='ISACTIVE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='REMOVE',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='删除标志'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='UPDATEBY',
            field=models.IntegerField(blank=True, null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='UPDATED',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='访问日期'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='离开日期'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='义工id'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='id_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='imgset_dir',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='图像目录'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='义工姓名'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='头像路径'),
        ),
    ]
