from django.db import models

# Create your models here.

class oldperson_info(models.Model):
    ID = models.AutoField(primary_key=True, verbose_name="老人id")
    ORG_ID = models.IntegerField(blank=True, null=True)
    CLIENT_ID = models.IntegerField(blank=True, null=True)
    username = models.CharField(blank=True, null=True, max_length=50, verbose_name="老人姓名")
    gender = models.CharField(blank=True, null=True, max_length=10, verbose_name="性别")
    phone = models.CharField(blank=True, null=True, max_length=50, verbose_name="电话")
    id_card = models.CharField(blank=True, null=True, max_length=50, verbose_name="身份证号")
    birthday = models.DateTimeField(blank=True, null=True, verbose_name="出生日期")
    checkin_date = models.DateTimeField(blank=True, null=True, verbose_name="入养老院日期")
    checkout_date = models.DateTimeField(blank=True, null=True, verbose_name="离开养老院日期")
    imgset_dir = models.CharField(blank=True, null=True, max_length=200, verbose_name="图像目录")
    profile_photo = models.CharField(blank=True, null=True, max_length=200, verbose_name="头像路径")
    room_number = models.CharField(blank=True, null=True, max_length=50, verbose_name="房间号")
    firstguardian_name = models.CharField(blank=True, null=True, max_length=50, verbose_name="第一监护人姓名")
    firstguardian_relationship = models.CharField(blank=True, null=True, max_length=50, verbose_name="与第一监护人关系")
    firstguardian_phone = models.CharField(blank=True, null=True, max_length=50, verbose_name="第一监护人电话")
    firstguardian_wechat = models.CharField(blank=True, null=True, max_length=50, verbose_name="第一监护人微信")
    secondguardian_name = models.CharField(blank=True, null=True, max_length=50, verbose_name="第二监护人姓名")
    secondguardian_relationship = models.CharField(blank=True, null=True, max_length=50, verbose_name="与第二监护人关系")
    secondguardian_phone = models.CharField(blank=True, null=True, max_length=50, verbose_name="第二监护人电话")
    secondguardian_wechat = models.CharField(blank=True, null=True, max_length=50, verbose_name="第二监护人微信")
    health_state = models.CharField(blank=True, null=True, max_length=50, verbose_name="健康状况")
    DESCRIPTION = models.CharField(blank=True, null=True, max_length=200, verbose_name="描述")
    ISACTIVE = models.CharField(blank=True, null=True, max_length=10, verbose_name="是否有效")
    CREATED = models.DateTimeField(blank=True, null=True, verbose_name="创建时间")
    CREATEBY = models.IntegerField(blank=True, null=True, verbose_name="创建人")
    UPDATED = models.DateTimeField(blank=True, null=True, verbose_name="更新时间")
    UPDATEBY = models.IntegerField(blank=True, null=True, verbose_name="更新人")
    REMOVE = models.CharField(blank=True, null=True, max_length=10, verbose_name="删除标志")

class employee_info(models.Model):
    id = models.AutoField(primary_key=True, verbose_name="工作人员id")
    ORG_ID = models.IntegerField(blank=True, null=True)
    CLIENT_ID = models.IntegerField(blank=True, null=True)
    username = models.CharField(blank=True, null=True, max_length=50, verbose_name="工作人员姓名")
    gender = models.CharField(blank=True, null=True, max_length=10, verbose_name="性别")
    phone = models.CharField(blank=True, null=True, max_length=50, verbose_name="电话")
    id_card = models.CharField(blank=True, null=True, max_length=50, verbose_name="身份证号")
    birthday = models.DateTimeField(blank=True, null=True, verbose_name="出生日期")
    hire_date = models.DateTimeField(blank=True, null=True, verbose_name="入职日期")
    resign_date = models.DateTimeField(blank=True, null=True, verbose_name="离职日期")
    imgset_dir = models.CharField(blank=True, null=True, max_length=200, verbose_name="图像目录")
    profile_photo = models.CharField(blank=True, null=True, max_length=200, verbose_name="头像路径")
    DESCRIPTION = models.CharField(blank=True, null=True, max_length=200, verbose_name="描述")
    ISACTIVE = models.CharField(blank=True, null=True, max_length=10, verbose_name="是否有效")
    CREATED = models.DateTimeField(blank=True, null=True, verbose_name="创建时间")
    CREATEBY = models.IntegerField(blank=True, null=True, verbose_name="创建人")
    UPDATED = models.DateTimeField(blank=True, null=True, verbose_name="更新时间")
    UPDATEBY = models.IntegerField(blank=True, null=True, verbose_name="更新人")
    REMOVE = models.CharField(blank=True, null=True, max_length=10, verbose_name="删除标志")

class volunteer_info(models.Model):
    id = models.AutoField(primary_key=True, verbose_name="义工id")
    ORG_ID = models.IntegerField(blank=True, null=True)
    CLIENT_ID = models.IntegerField(blank=True, null=True)
    name = models.CharField(blank=True, null=True, max_length=50, verbose_name="义工姓名")
    gender = models.CharField(blank=True, null=True, max_length=10, verbose_name="性别")
    phone = models.CharField(blank=True, null=True, max_length=50, verbose_name="电话")
    id_card = models.CharField(blank=True, null=True, max_length=50, verbose_name="身份证号")
    birthday = models.DateTimeField(blank=True, null=True, verbose_name="出生日期")
    checkin_date = models.DateTimeField(blank=True, null=True, verbose_name="访问日期")
    checkout_date = models.DateTimeField(blank=True, null=True, verbose_name="离开日期")
    imgset_dir = models.CharField(blank=True, null=True, max_length=200, verbose_name="图像目录")
    profile_photo = models.CharField(blank=True, null=True, max_length=200, verbose_name="头像路径")
    DESCRIPTION = models.CharField(blank=True, null=True, max_length=200, verbose_name="描述")
    ISACTIVE = models.CharField(blank=True, null=True, max_length=10, verbose_name="是否有效")
    CREATED = models.DateTimeField(blank=True, null=True, verbose_name="创建时间")
    CREATEBY = models.IntegerField(blank=True, null=True, verbose_name="创建人")
    UPDATED = models.DateTimeField(blank=True, null=True, verbose_name="更新时间")
    UPDATEBY = models.IntegerField(blank=True, null=True, verbose_name="更新人")
    REMOVE = models.CharField(blank=True, null=True, max_length=10, verbose_name="删除标志")

class event_info(models.Model):
    id = models.AutoField(primary_key=True, verbose_name="事件id")
    event_type = models.IntegerField(blank=True, null=True, verbose_name="事件类型")
    event_date = models.DateTimeField(blank=True, null=True, verbose_name="事件发生的时间")
    event_location = models.CharField(blank=True, null=True, max_length=200, verbose_name="事件发生的地点")
    event_desc = models.CharField(blank=True, null=True, max_length=200, verbose_name="事件描述")
    oldperson_id = models.IntegerField(blank=True, null=True, verbose_name="老人id")

class sys_user(models.Model):
    ID = models.AutoField(primary_key=True, verbose_name="系统管理员id")
    ORG_ID = models.IntegerField(blank=True, null=True)
    CLIENT_ID = models.IntegerField(blank=True, null=True)
    UserName = models.CharField(blank=True, null=True, max_length=50, verbose_name="用户名")
    Password = models.CharField(blank=True, null=True, max_length=50, verbose_name="密码")
    REAL_NAME = models.CharField(blank=True, null=True, max_length=50, verbose_name="用户真实姓名")
    SEX = models.CharField(blank=True, null=True, max_length=50, verbose_name="性别")
    EMAIL = models.CharField(blank=True, null=True, max_length=50, verbose_name="邮箱")
    PHONE = models.CharField(blank=True, null=True, max_length=50, verbose_name="电话")
    MOBILE = models.CharField(blank=True, null=True, max_length=50, verbose_name="移动电话")
    DESCRIPTION = models.CharField(blank=True, null=True, max_length=200, verbose_name="描述")
    ISACTIVE = models.CharField(blank=True, null=True, max_length=10, verbose_name="是否有效")
    CREATED = models.DateTimeField(blank=True, null=True, verbose_name="创建时间")
    CREATEBY = models.IntegerField(blank=True, null=True, verbose_name="创建人")
    UPDATED = models.DateTimeField(blank=True, null=True, verbose_name="更新时间")
    UPDATEBY = models.IntegerField(blank=True, null=True, verbose_name="更新人")
    REMOVE = models.CharField(blank=True, null=True, max_length=10, verbose_name="删除标志")
    DATAFILTER = models.CharField(blank=True, null=True, max_length=200, verbose_name="数据过滤")
    theme = models.CharField(blank=True, null=True, max_length=45, verbose_name="主题")
    defaultpage = models.CharField(blank=True, null=True, max_length=45, verbose_name="缺省页面")
    logoimage = models.CharField(blank=True, null=True, max_length=45, verbose_name="Logo")
    qqopenid = models.CharField(blank=True, null=True, max_length=100, verbose_name="用于第三方登录的凭证")
    appversion = models.CharField(blank=True, null=True, max_length=10, verbose_name="检测app的版本号")
    jsonauth = models.CharField(blank=True, null=True, max_length=1000, verbose_name="用于app的权限控制")




