from django.db import models

# Create your models here.

class oldperson_info(models.Model):
    ID = models.IntegerField(primary_key=True)
    ORG_ID = models.IntegerField(blank=True, null=True)
    CLIENT_ID = models.IntegerField(blank=True, null=True)
    username = models.CharField(blank=True, null=True, max_length=50)
    gender = models.CharField(blank=True, null=True, max_length=10)
    phone = models.CharField(blank=True, null=True, max_length=50)
    id_card = models.CharField(blank=True, null=True, max_length=50)
    birthday = models.DateTimeField(blank=True, null=True)
    checkin_date = models.DateTimeField(blank=True, null=True)
    checkout_date = models.DateTimeField(blank=True, null=True)
    imgset_dir = models.CharField(blank=True, null=True, max_length=200)
    profile_photo = models.CharField(blank=True, null=True, max_length=200)
    room_number = models.CharField(blank=True, null=True, max_length=50)
    firstguardian_name = models.CharField(blank=True, null=True, max_length=50)
    firstguardian_relationship = models.CharField(blank=True, null=True, max_length=50)
    firstguardian_phone = models.CharField(blank=True, null=True, max_length=50)
    firstguardian_wechat = models.CharField(blank=True, null=True, max_length=50)
    secondguardian_name = models.CharField(blank=True, null=True, max_length=50)
    secondguardian_relationship = models.CharField(blank=True, null=True, max_length=50)
    secondguardian_phone = models.CharField(blank=True, null=True, max_length=50)
    secondguardian_wechat = models.CharField(blank=True, null=True, max_length=50)
    health_state = models.CharField(blank=True, null=True, max_length=50)
    DESCRIPTION = models.CharField(blank=True, null=True, max_length=200)
    ISACTIVE = models.CharField(blank=True, null=True, max_length=10)
    CREATED = models.DateTimeField(blank=True, null=True)
    CREATEBY = models.IntegerField(blank=True, null=True)
    UPDATED = models.DateTimeField(blank=True, null=True)
    UPDATEBY = models.IntegerField(blank=True, null=True)
    REMOVE = models.CharField(blank=True, null=True, max_length=10)

class employee_info(models.Model):
    id = models.IntegerField(primary_key=True)
    ORG_ID = models.IntegerField(blank=True, null=True)
    CLIENT_ID = models.IntegerField(blank=True, null=True)
    username = models.CharField(blank=True, null=True, max_length=50)
    gender = models.CharField(blank=True, null=True, max_length=10)
    phone = models.CharField(blank=True, null=True, max_length=50)
    id_card = models.CharField(blank=True, null=True, max_length=50)
    birthday = models.DateTimeField(blank=True, null=True)
    hire_date = models.DateTimeField(blank=True, null=True)
    resign_date = models.DateTimeField(blank=True, null=True)
    imgset_dir = models.CharField(blank=True, null=True, max_length=200)
    profile_photo = models.CharField(blank=True, null=True, max_length=200)
    DESCRIPTION = models.CharField(blank=True, null=True, max_length=200)
    ISACTIVE = models.CharField(blank=True, null=True, max_length=10)
    CREATED = models.DateTimeField(blank=True, null=True)
    CREATEBY = models.IntegerField(blank=True, null=True)
    UPDATED = models.DateTimeField(blank=True, null=True)
    UPDATEBY = models.IntegerField(blank=True, null=True)
    REMOVE = models.CharField(blank=True, null=True, max_length=10)

class volunteer_info(models.Model):
    id = models.IntegerField(primary_key=True)
    ORG_ID = models.IntegerField(blank=True, null=True)
    CLIENT_ID = models.IntegerField(blank=True, null=True)
    name = models.CharField(blank=True, null=True, max_length=50)
    gender = models.CharField(blank=True, null=True, max_length=10)
    phone = models.CharField(blank=True, null=True, max_length=50)
    id_card = models.CharField(blank=True, null=True, max_length=50)
    birthday = models.DateTimeField(blank=True, null=True)
    checkin_date = models.DateTimeField(blank=True, null=True)
    checkout_date = models.DateTimeField(blank=True, null=True)
    imgset_dir = models.CharField(blank=True, null=True, max_length=200)
    profile_photo = models.CharField(blank=True, null=True, max_length=200)
    DESCRIPTION = models.CharField(blank=True, null=True, max_length=200)
    ISACTIVE = models.CharField(blank=True, null=True, max_length=10)
    CREATED = models.DateTimeField(blank=True, null=True)
    CREATEBY = models.IntegerField(blank=True, null=True)
    UPDATED = models.DateTimeField(blank=True, null=True)
    UPDATEBY = models.IntegerField(blank=True, null=True)
    REMOVE = models.CharField(blank=True, null=True, max_length=10)

class event_info(models.Model):
    id = models.IntegerField(primary_key=True)
    event_type = models.IntegerField(blank=True, null=True)
    event_date = models.DateTimeField(blank=True, null=True)
    event_location = models.CharField(blank=True, null=True, max_length=200)
    event_desc = models.CharField(blank=True, null=True, max_length=200)
    oldperson_id = models.IntegerField(blank=True, null=True)

class sys_user(models.Model):
    ID = models.IntegerField(primary_key=True)
    ORG_ID = models.IntegerField(blank=True, null=True)
    CLIENT_ID = models.IntegerField(blank=True, null=True)
    UserName = models.CharField(blank=True, null=True, max_length=50)
    Password = models.CharField(blank=True, null=True, max_length=50)
    REAL_NAME = models.CharField(blank=True, null=True, max_length=50)
    SEX = models.CharField(blank=True, null=True, max_length=50)
    EMAIL = models.CharField(blank=True, null=True, max_length=50)
    PHONE = models.CharField(blank=True, null=True, max_length=50)
    MOBILE = models.CharField(blank=True, null=True, max_length=50)
    DESCRIPTION = models.CharField(blank=True, null=True, max_length=200)
    ISACTIVE = models.CharField(blank=True, null=True, max_length=10)
    CREATED = models.DateTimeField(blank=True, null=True)
    CREATEBY = models.IntegerField(blank=True, null=True)
    UPDATED = models.DateTimeField(blank=True, null=True)
    UPDATEBY = models.IntegerField(blank=True, null=True)
    REMOVE = models.CharField(blank=True, null=True, max_length=10)
    DATAFILTER = models.CharField(blank=True, null=True, max_length=200)
    theme = models.CharField(blank=True, null=True, max_length=45)
    defaultpage = models.CharField(blank=True, null=True, max_length=45)
    logoimage = models.CharField(blank=True, null=True, max_length=45)
    qqopenid = models.CharField(blank=True, null=True, max_length=100)
    appversion = models.CharField(blank=True, null=True, max_length=10)
    jsonauth = models.CharField(blank=True, null=True, max_length=1000)




